# Generated by Django 4.2.5 on 2023-09-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("login", "Probleme beim login"),
                            ("register", "Probleme beim registrieren"),
                            ("improvement", "Verbesserungsvorschläge"),
                            ("problems", "Probleme mit der Website"),
                            ("others", "Sonstiges"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "how_to_contact",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("call", "Anrufen"),
                            ("WhatsApp", "WhatsApp"),
                        ],
                        max_length=200,
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("email_phone", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=2000)),
                ("seen", models.BooleanField(default=False)),
                ("important", models.BooleanField(default=False)),
                ("in_process", models.BooleanField(default=False)),
                ("finished", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=50)),
                ("hashed_password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("media", models.BinaryField()),
                ("description", models.CharField(max_length=1000)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_site.user"
                    ),
                ),
            ],
        ),
    ]
