# Generated by Django 4.2.5 on 2023-09-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=50)),
                ("hashed_password", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="DiaryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="media/images/")),
                ("videos", models.FileField(upload_to="media/videos/")),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_files",
                        to="my_site.diary",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="diary",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_site.user"
            ),
        ),
        migrations.AddField(
            model_name="diary",
            name="files",
            field=models.ManyToManyField(
                related_name="diary_entries", to="my_site.diaryfile"
            ),
        ),
    ]
