# Generated by Django 4.2.5 on 2023-09-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
