# Generated by Django 4.2.5 on 2023-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key",
            field=models.CharField(default=False, max_length=128),
            preserve_default=False,
        ),
    ]
