# Generated by Django 4.2.5 on 2023-09-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0002_user_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="media",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
