# Generated by Django 4.2.5 on 2023-09-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0003_alter_diary_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="created_at",
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
