# Generated by Django 4.2.5 on 2023-09-16 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0004_diary_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="media",
        ),
        migrations.AddField(
            model_name="diary",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media/user_files/images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="videos",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="media/user_files/videos/"
            ),
            preserve_default=False,
        ),
    ]
