# Generated by Django 4.2.5 on 2023-09-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0006_alter_diary_image_alter_diary_videos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diary",
            old_name="videos",
            new_name="video",
        ),
    ]
