# Generated by Django 4.2.5 on 2023-09-18 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0007_rename_videos_diary_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="image",
        ),
        migrations.RemoveField(
            model_name="diary",
            name="video",
        ),
        migrations.AddField(
            model_name="diary",
            name="media",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media/users_media/"
            ),
            preserve_default=False,
        ),
    ]
