# Generated by Django 4.2.5 on 2023-09-18 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0008_remove_diary_image_remove_diary_video_diary_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="media",
        ),
        migrations.AddField(
            model_name="diary",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media/images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="video",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="media/videos/"
            ),
            preserve_default=False,
        ),
    ]
