# Generated by Django 4.2.5 on 2023-09-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0009_remove_diary_media_diary_image_diary_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diary",
            old_name="image",
            new_name="images",
        ),
        migrations.RenameField(
            model_name="diary",
            old_name="video",
            new_name="videos",
        ),
    ]
