# Generated by Django 4.2.5 on 2023-09-18 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0010_rename_image_diary_images_rename_video_diary_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="images",
        ),
        migrations.RemoveField(
            model_name="diary",
            name="videos",
        ),
        migrations.CreateModel(
            name="DiaryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="media/images/")),
                ("videos", models.FileField(upload_to="media/videos/")),
                (
                    "diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_site.diary"
                    ),
                ),
            ],
        ),
    ]
