# Generated by Django 4.2.5 on 2023-09-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0011_remove_diary_images_remove_diary_videos_diaryfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="files",
            field=models.ManyToManyField(
                related_name="diary_entries", to="my_site.diaryfile"
            ),
        ),
        migrations.AlterField(
            model_name="diaryfile",
            name="diary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_files",
                to="my_site.diary",
            ),
        ),
    ]
