# Generated by Django 4.2.5 on 2023-09-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_site", "0013_alter_diary_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="description",
            field=models.TextField(),
        ),
    ]
